/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;

public class SquadTest{
	@After
	public void tearDown(){
		
		Squad.clear();
	}
	
	
	Squad testSquad = new Squad("marvel", "fight");
	Squad firstSquad = new Squad("marvel", "fight");
	Squad secondSquad = new Squad("dc","make shitty movies");
  Hero testHero = new Hero("buttman",34,"spots big butts","small butts");
	
	
	
  @Test
	public void squad_instantiatesCorrectly_true(){
		assertEquals(true,testSquad instanceof Squad);
	}
	
		@Test
	public void Hero_instantiatesWithProperties_String(){
		assertThat(testSquad.getName(),is(equalTo("marvel")));
    assertThat(testSquad.getCause(), is(equalTo("fight")));
 
	}
	
	@Test
	public void all_returnsAllInstancesOfSquad_true(){
		assertEquals(true, Squad.all().contains(firstSquad));
		assertEquals(true, Squad.all().contains(secondSquad));
	}
	
	@Test
	public void clear_emptiesAllSquadFromList_0(){
		Squad.clear();
		assertEquals(Squad.all().size(), 0);
	}
	
	@Test
	public void getId_squadInstantiateWithAnId_1(){
		assertEquals(1,testSquad.getId());
	}
	
	@Test
  public void find_returnsSquadWithSameId_secondSquad() {
    
 
    assertEquals(Squad.find(secondSquad.getId()), secondSquad);
  }
	
	@Test
  public void getHeroes_initiallyReturnsEmptyList_ArrayList() {
		assertEquals(0, testSquad.getHeroes().size());
	}
	
	@Test
	public void addHero_addsHeroToList_true() {
  testSquad.addHero(testHero);
  assertTrue(testSquad.getHeroes().contains(testHero));
	}


	
}
